version: "3.9"
services:
  redis:
    image: redis:6-alpine
    container_name: corp_portal_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - corp_net

  db:
    image: postgres:15-alpine
    container_name: corp_portal_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - corp_net

  app:
    build: .
    container_name: corp_portal_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - corp_net

networks:
  corp_net:
    driver: bridge

volumes:
  db_data:
